import time
f = open("comments.txt", "a+")
print("Hello and welcome to your virtual baby!")
print(" **Side Note: Please type your answers exactly as written in question :) \n ")
name = input("What would you like to name your child? \n")
time.sleep(2)
print("Loading...")
time.sleep(1)
print("Loading...")
time.sleep(1)
print("Congratulations on the birth of "+(name)+"!")
time.sleep(3)
gender = input("Would you like "+(name)+" to be a boy or a girl? \n")
if(gender=="boy" or gender == "Boy"):
    pronoun = "he"
    pronoun2 = "him"
    pronoun3 = "his"
    time.sleep(3)
    print("\n                                  /)                ")
    print("                                 /  )               ")
    print("         Its a boy!!!!          /   )               ")
    print("                               /     )              ")
    print("                              /     )               ")
    print("                             /      )               ")
    print("                            /      )                ")
    print("                _____   /^^/        )^^^^^^\        ")
    print("          __x__/  o   \/  /        )  /  /  \       ")
    print("         <_____                 )            \      ")
    print("           / \  \__                          /      ")
    print("          /   \     \____                   /       ")
    print("         /     \         --------        __/        ")
    print("        /       \                 -------           ")
    print("       (         )                                  ")
    print("        --     --                                   ")
    print("          --- -                                     ")
    print("                                                    ")
elif(gender=="girl" or gender == "Girl"):
    pronoun = "she"
    pronoun2 = "her"
    pronoun3 = "her"
    time.sleep(3)
    print("\n                                  /)                ")
    print("                                 /  )               ")
    print("         Its a girl!!!!         /   )               ")
    print("                               /     )              ")
    print("                              /     )               ")
    print("                             /      )               ")
    print("                            /      )                ")
    print("                _____   /^^/        )^^^^^^\        ")
    print("          __x__/  o   \/  /        )  /  /  \       ")
    print("         <_____                 )            \      ")
    print("           / \  \__                          /      ")
    print("          /   \     \____                   /       ")
    print("         /     \         --------        __/        ")
    print("       /       \                 -------            ")
    print("       (         )                                  ")
    print("        --     --                                   ")
    print("          --- -                                     ")
    print("                                                    ")
print((name)+" is on "+(pronoun3)+ " way! \n")
time.sleep(4)
print("Wow "+(name)+" is so cuteeee!")
print("              _)_")
print("           .-'(/ '-.")
print("          /    `    \ ")
print("         /  -     -  \ ")
print("        (`  a     a  `)")     
print("         \     ^     /")        
print("          '. '---' .'")         
print("          .-`'---'`-.")          
print("         /           \ ")
print("        /  / '   ' \  \ ")
print("      _/  /|       |\  \_")
print("     `/|\` |+++++++|`/|\`")
print("          /\       /\ ")
print("          | `-._.-` |")
print("          \   / \   /")
print("          |_ |   | _|")
print("          | _|   |_ |")
print("          (ooO   Ooo)")
time.sleep(5)
hunger = input((name)+" is now 3 months old, but "+(pronoun)+" is crying and hungry! What type of food would like to feed "+(pronoun2)+"? Would you like to feed "+(pronoun2)+" baby formula, \n milk, or applesauce? \n")
print("                        _")
print("     .--(-.        -`-_..'")
print("     '      '       /)'-.`.  .'")
print("    c'  ^ ^ '       `_) `-_)'")
print("     '. `--''_        `)  \ BP")
print("    .'`----' `.        \..'")
print("    '         /'.*o")
print("    `.       '\_o*")
print("      '.  -__`--'")
time.sleep(3)
if(hunger == "baby formula"):
    print("Yay!!! Thankfully "+(name)+" stopped crying!! This is all thanks to your amazing parenting!!")
if(hunger == "milk"):
    print("Aw man, "+(name)+" does not want milk!")
    time.sleep(3)
    wrongmilk = input("What would you like to feed "+(pronoun2)+": baby formula or applesauce? \n")
    if(wrongmilk == "baby formula"):
        print("Yay!!! Thankfully "+(name)+" stopped crying!! This is all thanks to your amazing parenting!!")
    if(wrongmilk == "applesauce"):
        print("Aw man, "+(name)+" does not want applesauce!")
        time.sleep(3)
        wrongapple = input("Would you like to feed "+(pronoun2)+" baby formula? \n")
        if(wrongapple == "yes"):
            print("Yay!!! Thankfully "+(name)+" stopped crying!! This is all thanks to your amazing parenting!!")
        if(wrongapple == "no"):
            print("Oh no, your baby is still crying, but you can't do anything about it! Just listen to your child cry, because you refused to give"+(pronoun2)+"baby formula!")
if(hunger == "applesauce"):
    print("Aw man, "+(name)+" does not want applesauce!")
    time.sleep(3)
    wrongapple2 = input("What would you like to feed "+(pronoun2)+": baby formula or milk? \n")
    if(wrongapple2 == "baby formula"):
        print("Yay!!! Thankfully "+(name)+" stopped crying!! This is all thanks to your amazing parenting!!")
    if(wrongapple2 == "milk"):
        print("Aw man, "+(name)+" does not want milk!")
        time.sleep(3)
        wrongmilk2 = input("Would you like to feed "+(pronoun2)+": baby formula? \n")
        if(wrongmilk2 == "yes" or wrongmilk2 == "baby formula"):
            print("Yay!!! Thankfully "+(name)+" stopped crying!! This is all thanks to your amazing parenting!!")
        if(wrongmilk2 == "no"):
            print("Oh no, your baby is still crying, but you can't do anything about it! Just listen to your child cry, because you refused to give "+(pronoun2)+" baby formula!")
time.sleep(5)
print("\n \n Quick Tips: \n > Formula fed babies take 2 to 3 oz of formula about 8 to 12 times a day. \n > At 5 months, along with formula, the baby can now eat solids. \n > After 12 months, they can transition from formula to regular milk.\n \n")
time.sleep(5)
print((name)+ " is now six months old! Woohoo!! \n ")
print("           _.~._")
print("        ,~'.~@~.`~.")
print("       / : _..._ : \ ")
print("      ( :,"''   ".: ) ")
print("       `C) 9 _ 9 (--.._,-  ____")
print("        (  )(@)(  )             `. ")
print("         `-.___.-'                \ ")
print("         ,' \ /    ,`             ;`-._,-.")
print("       ,'  ,'/   ,'           `---t.,-.   \_")
print("     ,--.,','  ,'----.__\         _(   \----'")
print("   '///,`,--.,'          `-.__.--'  `.  )")
print("       '///,'                         `-`   ")
time.sleep(4)
sick = input("Come quick, "+(name)+" has had a high fever since this morning. Will you clear "+(pronoun3)+" nose with a syringe, take \n"+(pronoun2)+" to the doctor ASAP, or moisten the dry air with a humidifier? \n")
if (sick == "clear "+(pronoun3)+" nose with a syringe"):
    print("Oh no!! This is a very dangerous situation!! Please do not choose this option!!")
    time.sleep(3)
    nosewrong = input("Will you take "+(pronoun2)+" to the doctor ASAP, or moisten the dry air with a humidifier? \n")
    if (nosewrong == "moisten the dry air with a humidifier"):
        print("Oh no!! This is a very dangerous situation!! Please do not choose this option!!")
        time.sleep(3)
        humidwrong2 = input("Will you take "+(pronoun2)+" to the doctor ASAP? \n")
        if(humidwrong2 == "yes"):
            print("Yayayay! "+(name)+" is healthy again! The doctor prescribed some medicines and fluids for "+(name)+" and "+(pronoun)+" is all better!")
        elif(humidwrong2 == "no"):
            print("Oh no, your baby is still crying, but you can't do anything about it! Just listen to your child cry and continue to watch"+(name)+"feel sick, because you refused to take"+(pronoun2)+" to the doctor!")
    elif (nosewrong == "take "+(pronoun2)+" to the doctor ASAP"):
        print("Yayayay! "+(name)+" is healthy again! The doctor prescribed some medicines and fluids for "+(name)+" and "+(pronoun)+" is all better!")
if (sick == "moisten the dry air with a humidifier"):
    print("Oh no!! This is a very dangerous situation!! Please do not choose this option!!")
    time.sleep(3)
    humidwrong = input("Will you clear "+(pronoun3)+" nose with a syringe or take "+(pronoun2)+" to the doctor ASAP? \n")
    if (humidwrong == "clear "+(pronoun3)+" nose with a syringe"):
        print("Oh no!! This is a very dangerous situation!! Please do not choose this option!!")
        time.sleep(3)
        nosewrong2 = input("Will you take"+(pronoun2)+"to the doctor ASAP? \n")
        if(nosewrong2 == "yes"):
            print("Yayayay! "+(name)+" is healthy again! The doctor prescribed some medicines and fluids for "+(name)+" and "+(pronoun)+"is all better!")
        elif(nosewrong2 == "no"):
            print("Oh no, your baby is still crying, but you can't do anything about it! Just listen to your child cry and continue to feel sick, because you refused to take "+(pronoun2)+" to the doctor!")
    elif (humidwrong == "take "+(pronoun2)+" to the doctor ASAP"):
        print("Yayayay! "+(name)+" is healthy again! The doctor prescribed some medicines and fluids for "+(name)+" and "+(pronoun)+" is all better!")
    elif (sick == "take "+(pronoun2)+" to the doctor"):
        print("Yayayay! "+(name)+" is healthy again! The doctor prescribed some medicines and fluids for "+(name)+" and "+(pronoun)+"is all better!")
print("        .----. ")
print("       ===(_)==")
print("      // 6  6 \\  ")
print("      (    7   )")
print("       \ '--' /")
print("        \_ ._/")
print("       __)  (__")
print("     /`/`\`V/`\`\ ")
print("   /   \  `Y _/_ \ ")
print("  / [DR]\_ |/ / /\ ")
print("  |     ( \/ / / / ")
print("   \  \  \      / ")
print("    \  `-/`  _.` ")
print("     `=._`=./ ")
time.sleep(2)
print("\n \n Quick Tips:\n > The most sickness in a baby is the common cold. You can expect for them to experience 5 bouts. \n > If you see these dangerous symptoms in your baby, see a doctor immediately: \n   - fever \n   - jaundice \n   - unsettling rashes \n   - Breathing problems")
time.sleep(5)
sleep = input("\n \n" +(name)+" has finally turned 9 months old!! Congratulations! However "+(pronoun)+" has been having a very difficult time sleeping soundly! Do you want to help "+(name)+" \n fall asleep by singing a lullaby, rocking "+(pronoun3)+" in your arms, or placing "+(pronoun3)+" in a crib? \n")
print("            .-'''-_  ")
print("          .'       `( \ ")
print("        @/            ')   ,--,__,-'")
print("        /        /      \ /     /   _/")
print("      __|           ,   |/         /")
print("    .~  `\   / \ ,  |   /")
print("  .~      `\    `  /  _/   _/")
print(".~          `\  ~~`__/    /")
print("~             `--'/")
print("             /   /    /")
print("            /  /'    /")
time.sleep(2)
if(sleep == "singing a lullaby" or "rocking "+(pronoun3)+" in your arms" or "rocking "+(pronoun3)+" in my arms" or "placing "+(pronoun3)+" in a crib"):
    print("YES! Congratulations! "+(name)+" went to sleep! Good job parenting!")
time.sleep(3)
print("            _.-'`'-._")
print("         .-'    _    '-.")
print("          `-.__  `\_.-'")
print("            |  `-``\| ")
print("            `-.....-A ")
print("Congratulations!!! You have completed the Virtual Baby app and now are ready to take care of a baby! :) ")
survey = input("\n Did you like the game? Yes or No?\n")
if (survey == "yes"):
    print("Thank you for your input and for playing our game!")
if(survey == "no"):
    why = input("Please tell us why you were not satisfied and we will take your comments into consideration for next time! \n")
    f.write(why)
    print("Thank you for playing!!")